#!/usr/bin/env bash

add_path() {
	if [[ -z $SHELL ]]; then
		echo "Failed to add path, could not identify shell profile"
		return 0
	fi

	local zshrc_files=.zshrc
	local bashrc_files=.bashrc
	local shprofile=$(basename "$SHELL")
	local shprofile_path=$HOME/$bashrc_files

	case $shprofile in
	zsh) shprofile_path=$HOME/$zshrc_files ;;
	*) echo "Unknown shell" exit 1 ;;
	esac

	if ! [[ -e $shprofile_path ]]; then
		touch "$shprofile_path"
	fi

	while read -r line; do echo "$line" | tee -a "$shprofile_path"; done
}
